import { RecommendationProvider } from "@/context/RecommendationContext";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { SessionProvider } from "@/components/providers/SessionProvider";
import { SocialAuthProvider } from "@/components/providers/SocialAuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <SocialAuthProvider>
            <RecommendationProvider>
              <AntdRegistry>{children}</AntdRegistry>
            </RecommendationProvider>
          </SocialAuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
