import { RecommendationProvider } from "@/context/RecommendationContext";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecommendationProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </RecommendationProvider>
      </body>
    </html>
  );
}
